name: test_env_xarrayutils
channels:
  - conda-forge
dependencies:
  - python=3.6
  - xarray < 0.15
  - numpy
  - future
  - scipy
  - black
  - matplotlib
  - pip
  - pip:
    - codecov
    - pytest-cov
